export const GET_ADDRESS_BOOK_LIST_REQUEST = "GET_ADDRESS_BOOK_LIST_REQUEST";
export const GET_ADDRESS_BOOK_LIST_SUCCESS = "GET_ADDRESS_BOOK_LIST_SUCCESS";
export const GET_ADDRESS_BOOK_LIST_FAILED = "GET_ADDRESS_BOOK_LIST_FAILED";

export const ADD_ADDRESS_REQUEST = "ADD_ADDRESS_REQUEST";
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS";
export const ADD_ADDRESS_FAILED = "ADD_ADDRESS_FAILED";

export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAILED = "DELETE_ADDRESS_FAILED";

export const EDIT_ADDRESS_REQUEST = "EDIT_ADDRESS_REQUEST";
export const EDIT_ADDRESS_SUCCESS = "EDIT_ADDRESS_SUCCESS";
export const EDIT_ADDRESS_FAILED = "EDIT_ADDRESS_FAILED";